# Generated by Django 4.1.7 on 2023-03-10 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOB', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('street_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=20)),
                ('zip_code', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientzenapi.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('patients', models.ManyToManyField(through='patientzenapi.PatientProvider', to='patientzenapi.patient')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_datetime', models.CharField(max_length=20)),
                ('visit_summary', models.CharField(max_length=500)),
                ('diagnosis', models.CharField(max_length=200)),
                ('treatment', models.CharField(max_length=500)),
                ('medication', models.CharField(max_length=500)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patientzenapi.patient')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patientzenapi.provider')),
            ],
        ),
        migrations.AddField(
            model_name='patientprovider',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientzenapi.provider'),
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('phone_number', models.CharField(max_length=20)),
                ('policy_number', models.CharField(max_length=12)),
                ('start_date', models.CharField(max_length=25)),
                ('end_date', models.CharField(max_length=25)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientzenapi.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('visit_summary', models.CharField(max_length=500)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientzenapi.office')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientzenapi.patient')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientzenapi.provider')),
            ],
        ),
    ]
